In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, confusion_matrix

np.random.seed(42)  # You can use any integer value
random_state = 42

In [2]:
modelNames = ["WW_redReward0_grReward1_7x7_300000steps",
                  "WW_redReward0_grReward1_7x7_1500000steps",
                  "WW_redReward1_grReward0_7x7_700000steps",
                  "WW_redReward1_grReward0_7x7_1500000steps",
                  "WW_redReward1_grReward0_7x7_2000000steps"]

modelNames = ["r00_g10_1500k",
              "r01_g10_1500k",
              "r02_g10_1500k",
              "r03_g10_1500k",
              "r04_g10_1500k",
              "r05_g10_1500k",
              "r06_g10_1500k",
              "r07_g10_1500k",
              "r08_g10_1500k",
              "r09_g10_1500k",
              "r10_g00_1500k",
              "r10_g01_1500k",
              "r10_g02_1500k",
              "r10_g03_1500k",
              "r10_g04_1500k",
              "r10_g05_1500k",
              "r10_g06_1500k",
              "r10_g07_1500k",
              "r10_g08_1500k",
              "r10_g09_1500k",
              "r10_g10_1500k"]

red0green1_30k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/WW_redReward0_grReward1_7x7_300000steps.csv",
    header=0,
    index_col=None,
    float_precision='high'
    )
red0green1_150k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/WW_redReward0_grReward1_7x7_1500000steps.csv",
    header=0,
    index_col=None,
    float_precision='high'
    )
red1green0_70k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/WW_redReward1_grReward0_7x7_700000steps.csv",
    header=0,          # Use first row as headers
    index_col=None,    # Don't use any column as index
    float_precision='high'  # For precise float values
    )
red1green0_150k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/WW_redReward1_grReward0_7x7_1500000steps.csv",
    header=0,          # Use first row as headers
    index_col=None,    # Don't use any column as index
    float_precision='high'  # For precise float values
    )
red1green0_200k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/WW_redReward1_grReward0_7x7_2000000steps.csv",
    header=0,          # Use first row as headers
    index_col=None,    # Don't use any column as index
    float_precision='high'  # For precise float values
    )

# all 21 act datasets
act_r00_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r00_g10_1500k.csv", header=0, index_col=None, float_precision='high')
act_r01_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r01_g10_1500k.csv", header=0, index_col=None, float_precision='high')
act_r02_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r02_g10_1500k.csv", header=0, index_col=None, float_precision='high')
act_r03_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r03_g10_1500k.csv", header=0, index_col=None, float_precision='high')
act_r04_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r04_g10_1500k.csv", header=0, index_col=None, float_precision='high')
act_r05_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r05_g10_1500k.csv", header=0, index_col=None, float_precision='high')
act_r06_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r06_g10_1500k.csv", header=0, index_col=None, float_precision='high')
act_r07_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r07_g10_1500k.csv", header=0, index_col=None, float_precision='high')
act_r08_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r08_g10_1500k.csv", header=0, index_col=None, float_precision='high')
act_r09_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r09_g10_1500k.csv", header=0, index_col=None, float_precision='high')
act_r10_g00_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r10_g00_1500k.csv", header=0, index_col=None, float_precision='high')
act_r10_g01_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r10_g01_1500k.csv", header=0, index_col=None, float_precision='high')
act_r10_g02_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r10_g02_1500k.csv", header=0, index_col=None, float_precision='high')
act_r10_g03_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r10_g03_1500k.csv", header=0, index_col=None, float_precision='high')
act_r10_g04_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r10_g04_1500k.csv", header=0, index_col=None, float_precision='high')
act_r10_g05_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r10_g05_1500k.csv", header=0, index_col=None, float_precision='high')
act_r10_g06_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r10_g06_1500k.csv", header=0, index_col=None, float_precision='high')
act_r10_g07_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r10_g07_1500k.csv", header=0, index_col=None, float_precision='high')
act_r10_g08_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r10_g08_1500k.csv", header=0, index_col=None, float_precision='high')
act_r10_g09_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r10_g09_1500k.csv", header=0, index_col=None, float_precision='high')
act_r10_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/act_r10_g10_1500k.csv", header=0, index_col=None, float_precision='high')

# all 21 shap datasets
shap_r00_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r00_g10_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r01_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r01_g10_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r02_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r02_g10_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r03_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r03_g10_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r04_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r04_g10_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r05_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r05_g10_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r06_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r06_g10_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r07_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r07_g10_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r08_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r08_g10_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r09_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r09_g10_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r10_g00_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r10_g00_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r10_g01_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r10_g01_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r10_g02_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r10_g02_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r10_g03_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r10_g03_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r10_g04_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r10_g04_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r10_g05_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r10_g05_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r10_g06_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r10_g06_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r10_g07_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r10_g07_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r10_g08_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r10_g08_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r10_g09_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r10_g09_1500k.csv", header=0, index_col=None, float_precision='high')
shap_r10_g10_1500k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/shap_r10_g10_1500k.csv", header=0, index_col=None, float_precision='high')





act_r00_g10_1500k.head()

target  agentX  agentY  redX  redY  greenX  greenY        a1        a2  \
0     1.0     4.0     0.0   1.0   3.0     0.0     0.0 -1.063813 -1.388111   
1     1.0     5.0     0.0   1.0   5.0     0.0     1.0 -1.309472 -1.589119   
2     1.0     5.0     6.0   1.0   1.0     0.0     1.0 -1.210390 -0.460016   
3     1.0     4.0     6.0   0.0   2.0     2.0     0.0 -1.193715 -1.286125   
4     1.0     5.0     6.0   1.0   3.0     1.0     1.0 -1.124752 -0.497009   

         a3  ...      a119      a120      a121      a122      a123      a124  \
0 -0.446459  ... -0.380181 -0.124317 -0.770996 -1.194992 -0.144317 -1.659807   
1 -0.476776  ... -0.303001 -0.137558 -1.042126 -1.403173 -0.171036 -1.773909   
2 -0.585106  ... -0.121769 -0.062525 -0.912727 -1.063136 -0.096144 -1.963744   
3 -0.464446  ... -0.226247 -0.107350 -0.762388 -1.203215 -0.195959 -1.943261   
4 -0.489893  ... -0.189787 -0.074102 -1.012939 -1.000071 -0.118401 -1.941515   

       a125      a126      a127      a128  
0 -0.131773 -0.184674 -0.160013 -0.458171  
1 -0.144172 -0.275801 -0.153738 -0.481150  
2 -0.161353 -0.140851 -0.204410 -0.235046  
3 -0.146536 -0.023378 -0.244318 -0.276013  
4 -0.167188 -0.055606 -0.241313 -0.200778  

[5 rows x 135 columns]

In [3]:
# Merge and shuffle the datasets
df = pd.concat([red0green1_30k, red0green1_150k, red1green0_70k, red1green0_200k], ignore_index=True)
df = df.sample(frac=1, random_state=random_state).reset_index(drop=True)

act_train = pd.concat([act_r01_g10_1500k, act_r02_g10_1500k, act_r03_g10_1500k, act_r04_g10_1500k, act_r05_g10_1500k, act_r06_g10_1500k, act_r07_g10_1500k, act_r08_g10_1500k, act_r09_g10_1500k, act_r10_g01_1500k, act_r10_g02_1500k, act_r10_g03_1500k, act_r10_g04_1500k, act_r10_g05_1500k, act_r10_g06_1500k, act_r10_g07_1500k, act_r10_g08_1500k, act_r10_g09_1500k], ignore_index=True)
act_train = act_train.sample(frac=1, random_state=random_state).reset_index(drop=True)
act_train = act_train.drop(["agentX","agentY","redX","redY","greenX","greenY"], axis=1)
act_df_test = pd.concat([act_r00_g10_1500k, act_r10_g10_1500k, act_r10_g00_1500k], ignore_index=True)
act_df_test = act_df_test.drop(["agentX","agentY","redX","redY","greenX","greenY"], axis=1)

act_x_train = act_train.drop('target', axis=1)
act_y_train = act_train['target']
act_x_test = act_df_test.drop('target', axis=1)
act_y_test = act_df_test['target']

shap_train = pd.concat([shap_r01_g10_1500k, shap_r02_g10_1500k, shap_r03_g10_1500k, shap_r04_g10_1500k, shap_r05_g10_1500k, shap_r06_g10_1500k, shap_r07_g10_1500k, shap_r08_g10_1500k, shap_r09_g10_1500k, shap_r10_g01_1500k, shap_r10_g02_1500k, shap_r10_g03_1500k, shap_r10_g04_1500k, shap_r10_g05_1500k, shap_r10_g06_1500k, shap_r10_g07_1500k, shap_r10_g08_1500k, shap_r10_g09_1500k], ignore_index=True)
shap_train = shap_train.sample(frac=1, random_state=random_state).reset_index(drop=True)
shap_test = pd.concat([shap_r00_g10_1500k, shap_r10_g10_1500k, shap_r10_g00_1500k], ignore_index=True)

shap_x_train = shap_train.drop('target', axis=1)
shap_y_train = shap_train['target']
shap_x_test = shap_test.drop('target', axis=1)
shap_y_test = shap_test['target']

In [4]:
actLinRegModel = LinearRegression()
actLinRegModel.fit(act_x_train, act_y_train)
act_y_pred = actLinRegModel.predict(act_x_test)
act_y_pred = np.clip(np.round(act_y_pred), -1, 1) # Round y_pred to int, max 1 and min -1
total_correct = (act_y_test == act_y_pred).sum()
total_samples = len(act_y_test)
print(f"Activation dataset")
print(f"Total correct predictions: {total_correct} out of {total_samples}")
print(f"Accuracy: {accuracy_score(act_y_test, act_y_pred):.2%}")
print(f"\nConfusion matrix:\n{confusion_matrix(act_y_test, act_y_pred)}")


Activation dataset
Total correct predictions: 847 out of 6000
Accuracy: 14.12%

Confusion matrix:
[[  71 1509 1396]
 [   2    3    4]
 [ 979 1263  773]]


In [5]:
shapLinRegModel = LinearRegression()
shapLinRegModel.fit(shap_x_train, shap_y_train)
shap_y_pred = shapLinRegModel.predict(shap_x_test)
shap_y_pred = np.clip(np.round(shap_y_pred), -1, 1) # Round y_pred to int, max 1 and min -1
total_correct = (shap_y_test == shap_y_pred).sum()
total_samples = len(shap_y_test)
print(f"Shap dataset")
print(f"Total correct predictions: {total_correct} out of {total_samples}")
print(f"Accuracy: {accuracy_score(shap_y_test, shap_y_pred):.2%}")
print(f"\nConfusion matrix:\n{confusion_matrix(shap_y_test, shap_y_pred)}")

Shap dataset
Total correct predictions: 6000 out of 6000
Accuracy: 100.00%

Confusion matrix:
[[3066    0    0]
 [   0   17    0]
 [   0    0 2917]]


In [6]:
actTreeModel = DecisionTreeClassifier(random_state=42)
actTreeModel.fit(act_x_train, act_y_train)
act_y_pred = actTreeModel.predict(act_x_test)
total_correct = (act_y_test == act_y_pred).sum()
total_samples = len(act_y_test)
print(f"Activation / Shap dataset")
print(f"Total correct predictions: {total_correct} out of {total_samples}")
print(f"Accuracy: {accuracy_score(act_y_test, act_y_pred):.2%}")
print(f"\nConfusion matrix:\n{confusion_matrix(act_y_test, act_y_pred)}")

Activation / Shap dataset
Total correct predictions: 1730 out of 6000
Accuracy: 28.83%

Confusion matrix:
[[ 947  391 1638]
 [   5    0    4]
 [1866  366  783]]


In [7]:
shapTreeModel = DecisionTreeClassifier(random_state=42)
shapTreeModel.fit(shap_x_train, shap_y_train)
shap_y_pred = shapTreeModel.predict(shap_x_test)
total_correct = (shap_y_test == shap_y_pred).sum()
total_samples = len(shap_y_test)
print(f"Activation / Shap dataset")
print(f"Total correct predictions: {total_correct} out of {total_samples}")
print(f"Accuracy: {accuracy_score(shap_y_test, shap_y_pred):.2%}")
print(f"\nConfusion matrix:\n{confusion_matrix(shap_y_test, shap_y_pred)}")

Activation / Shap dataset
Total correct predictions: 5094 out of 6000
Accuracy: 84.90%

Confusion matrix:
[[2801    6  259]
 [   2    6    9]
 [ 615   15 2287]]


An eeeeeven better baseline is established. When giving the classification models a network they hadn't seen before gave them a 0% accuracy.

Done:
- Train 21 models
- Create all activation and shap datasets
- Precicted unseen network datasets

Answered questions:
- Should the models retain the 5% epsilon during dataset creation? Yes
- Does the SHAP background data sound sound? Compare
- Should the decision tree recieve coordinates too? Format? Yes, no feature engineering

Meeting 2025-02-24

Next up:
- Implement Gradcam

Questions:
- Should I switch to an environment where the agent can't see the goal?
- What other XAI methods makes sense to implement after gradcam?

Notes:
