In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, confusion_matrix

np.random.seed(42)  # You can use any integer value
random_state = 42

In [2]:
modelNames = ["WW_redReward0_grReward1_7x7_300000steps",
                  "WW_redReward0_grReward1_7x7_1500000steps",
                  "WW_redReward1_grReward0_7x7_700000steps",
                  "WW_redReward1_grReward0_7x7_1500000steps",
                  "WW_redReward1_grReward0_7x7_2000000steps"]

red0green1_30k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/WW_redReward0_grReward1_7x7_300000steps.csv",
    header=0,
    index_col=None,
    float_precision='high'
    )
red0green1_150k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/WW_redReward0_grReward1_7x7_1500000steps.csv",
    header=0,
    index_col=None,
    float_precision='high'
    )
red1green0_70k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/WW_redReward1_grReward0_7x7_700000steps.csv",
    header=0,          # Use first row as headers
    index_col=None,    # Don't use any column as index
    float_precision='high'  # For precise float values
    )
red1green0_150k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/WW_redReward1_grReward0_7x7_1500000steps.csv",
    header=0,          # Use first row as headers
    index_col=None,    # Don't use any column as index
    float_precision='high'  # For precise float values
    )
red1green0_200k = pd.read_csv("C:/Projects/public/XAI_Master/datasets/WW_redReward1_grReward0_7x7_2000000steps.csv",
    header=0,          # Use first row as headers
    index_col=None,    # Don't use any column as index
    float_precision='high'  # For precise float values
    )


# Merge and shuffle the two datasets
df = pd.concat([red0green1_30k, red0green1_150k, red1green0_70k, red1green0_200k], ignore_index=True)
df = df.sample(frac=1, random_state=random_state).reset_index(drop=True)
"""
df = red0green1
"""
x = df.drop('target', axis=1)
x = df.drop(['target',"agentX","agentY","redX","redY","greenX","greenY"], axis=1)
print(x.shape)
y = df['target']

# x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=random_state)

# use red1green0_150k as test set
x_train = x
y_train = y
x_test = red1green0_150k.drop(['target',"agentX","agentY","redX","redY","greenX","greenY"], axis=1)
y_test = red1green0_150k['target']

(40000, 128)


In [3]:
# Train and make predictions
model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

# Print float results
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred):.4f}")
print(f"R2 Score: {r2_score(y_test, y_pred):.4f}")

# Round y_pred to int, max 1 and min -1
y_pred = np.clip(np.round(y_pred), -1, 1)

# Print int results
total_correct = (y_test == y_pred).sum()
total_samples = len(y_test)
print(f"Total correct predictions: {total_correct} out of {total_samples}")
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2%}")
print(f"\nConfusion matrix:\n{confusion_matrix(y_test, y_pred)}")


Mean Squared Error: 8.7399
R2 Score: -7953.1265
Total correct predictions: 3 out of 10000
Accuracy: 0.03%

Confusion matrix:
[[   0  241 9748]
 [   0    3    8]
 [   0    0    0]]


In [4]:
# Train and make predictions
tree = DecisionTreeClassifier(random_state=42)
tree.fit(x_train, y_train)
y_pred = tree.predict(x_test)

# Print results
total_correct = (y_test == y_pred).sum()
total_samples = len(y_test)
print(f"Total correct predictions: {total_correct} out of {total_samples}")
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2%}")
print(f"\nConfusion matrix:\n{confusion_matrix(y_test, y_pred)}")

Total correct predictions: 0 out of 10000
Accuracy: 0.00%

Confusion matrix:
[[   0  908 9081]
 [   0    0   11]
 [   0    0    0]]


An eeeeeven better baseline is established. When giving the classification models a network they hadn't seen before gave them a 0% accuracy.

Todo:
- Train many models, 30+
- Create shap datasets

Questions:
- Should the models retain the 5% epsilon during dataset creation? Yes
- Does the SHAP background data sound sound? Compare
- Should the decision tree recieve coordinates too? Format? Yes, no feature engineering

In [5]:
- Sette netverket som label
- Zero-shot


SyntaxError: invalid syntax (2854073663.py, line 1)